[package]
name = "langin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argin = "0.1.0"
lib-lexin = "0.1.2"


